# Generated by Django 3.1.14 on 2021-12-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('DRFT', 'Draft'), ('ACTV', 'Active'), ('DN', 'Done'), ('ARCH', 'Archived')], default='DRFT', max_length=4),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False),
        ),
    ]
