# Generated by Django 3.1.14 on 2021-12-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20211214_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('DRFT', 'Draft'), ('ACTV', 'Active'), ('DN', 'Done'), ('ARCH', 'Archived')], default='DRFT', editable=False, max_length=4),
        ),
    ]
